on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
    - name: Check module is tidy
      run: go mod tidy
    - name: Verify commit is clean
      run: test -z "$(git status --porcelain)" || (git status; git diff; false)
