on:
  push:
    branches:
      - master
  repository_dispatch:
  pull_request:
    branches:
      - '**'

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - name: Ensure latest CUE
      # The latest git clean check ensures that this call is effectively
      # side effect-free. Using GOPROXY=direct ensures we don't accidentally
      # hit a stale cache in the proxy.
      run: |
        GOPROXY=direct go get -d cuelang.org/go@latest
        cd play
        GOPROXY=direct go get -d github.com/cue-sh/playground@latest
    - name: Regenerate
      run: go generate ./...
    - name: Check module is tidy
      run: go mod tidy
    - name: Verify commit is clean
      run: test -z "$(git status --porcelain)" || (git status; git diff; false)
