on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - name: Ensure latest CUE
      run: go get -d cuelang.org/go@latest # the git clean check later catches this
    - name: Regenerate
      run: go generate ./...
    - name: Check module is tidy
      run: go mod tidy
    - name: Verify commit is clean
      run: test -z "$(git status --porcelain)" || (git status; git diff; false)
